# wrangler.toml (修正後)
name = "sazanami"
compatibility_date = "2025-06-27"

# Node.jsの互換機能を有効にするための設定
compatibility_flags = ["nodejs_compat"]

# ↓↓↓ これが、このファイルをPages用の設定だと認識させるための重要な一行です ↓↓↓
pages_build_output_dir = ".svelte-kit/cloudflare"