name = "sazanami-websocket"
compatibility_date = "2025-05-12"

[durable_objects]
bindings = [
  { name = "ROOM_SYNC", class_name = "RealtimeRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["RealtimeRoom"]

compatibility_flags = ["nodejs_compat"]
