<script lang="ts">
	import type { Note } from '$lib/types';
	import { invalidateAll } from '$app/navigation';
	import { formatDistanceToNow } from 'date-fns';
	import { ja } from 'date-fns/locale';
	import { createEventDispatcher } from 'svelte';
	import hljs from 'highlight.js';
	import { renderWikiLinks } from '$lib/utils/note-utils';
	import { sanitizeHtml, escapeHtml } from '$lib/utils/sanitize';
	import { customMarked } from '$lib/utils/markdown-renderer';

	export let note: Note & { tags: string[] };
	export let mode: 'timeline' | 'archive' | 'trash' = 'timeline';

	const dispatch = createEventDispatcher<{ edit: Note; delete: Note }>();

	type EmbedPlaceholder = {
		placeholder: string;
		title: string;
	};

	function escapeMarkdownText(value: string) {
		return value
			.replace(/\\/g, '\\\\')
			.replace(/\]/g, '\\]')
			.replace(/\(/g, '\\(')
			.replace(/\)/g, '\\)');
	}

	function protectNoteEmbeds(content: string) {
		const embeds: EmbedPlaceholder[] = [];
		const protectedContent = content.replace(/!\[\[(.*?)\]\]/g, (_match, title) => {
			const placeholder = `__SAZANAMI_NOTE_EMBED_${embeds.length}__`;
			embeds.push({ placeholder, title });
			return placeholder;
		});

		return { contentHtml: protectedContent, embeds };
	}

	function restoreNoteEmbeds(content: string, embeds: EmbedPlaceholder[]) {
		let restored = content;
		for (const embed of embeds) {
			const linkText = `埋め込み: ${escapeMarkdownText(embed.title)}`;
			const encodedTitle = encodeURIComponent(embed.title);
			restored = restored.replace(embed.placeholder, `[${linkText}](note-embed:${encodedTitle})`);
		}
		return restored;
	}

	// 埋め込み（![[...]]）を保護してからWikiLinkを解決し、最後にnote-embed:リンクとして復元
	$: noteEmbedsProtected = protectNoteEmbeds(note.content || '');
	$: processedContent = renderWikiLinks(noteEmbedsProtected.contentHtml, note.resolvedLinks);
	$: contentWithEmbeds = restoreNoteEmbeds(processedContent, noteEmbedsProtected.embeds);

	// Determine if the content is likely generated by Tiptap (already HTML)
	$: isHtmlContent = /<p>|<h[1-6]>|<ul|<ol|<blockquote|<pre|<div/i.test(contentWithEmbeds || '');

	function normalizeContentForStorage(text: string) {
		return text
			.replace(/\u00a0/g, ' ')
			.replace(/^[ \t]*&nbsp;[ \t]*$/gm, '')
			.replace(/&nbsp;/g, ' ');
	}

	// Action to manually apply enhancements (highlighting, copy buttons, interactive checkboxes)
	function enhanceProseContent(node: HTMLElement, _options?: unknown) {
		const applyEnhancements = () => {
			if (!node) return;
			node.querySelectorAll('pre').forEach((pre) => {
				if (!pre.parentElement?.classList.contains('code-block-wrapper')) {
					const wrapper = document.createElement('div');
					wrapper.className = 'code-block-wrapper';
					wrapper.style.position = 'relative';
					wrapper.style.margin = '1.5rem 0';
					pre.parentNode?.insertBefore(wrapper, pre);
					wrapper.appendChild(pre);
				}
			});

			node.querySelectorAll('.code-block-wrapper').forEach((wrapper) => {
				const block = wrapper.querySelector('pre code');
				if (block) {
					if (!block.classList.contains('hljs') && !block.hasAttribute('data-highlighted')) {
						hljs.highlightElement(block as HTMLElement);
						block.classList.add('hljs'); // Ensure the class is added just in case
					}

					// Add copy button if it doesn't exist
					if (!wrapper.querySelector('.copy-code-btn')) {
						wrapper.classList.add('group'); // For hover effect

						const button = document.createElement('button');
						button.className =
							'copy-code-btn btn btn-xs btn-square absolute right-2 top-2 opacity-0 transition-opacity z-10 bg-base-200/50 text-base-content hover:bg-base-300 border-none group-hover:opacity-100 backdrop-blur-sm';

						const copyIcon =
							'<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
						const checkIcon =
							'<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-success"><polyline points="20 6 9 17 4 12"></polyline></svg>';

						button.innerHTML = copyIcon;
						button.title = 'コードをコピー';

						button.onclick = async (e) => {
							e.stopPropagation();
							try {
								await navigator.clipboard.writeText(block.textContent || '');
								button.innerHTML = checkIcon;
								setTimeout(() => {
									if (button) button.innerHTML = copyIcon;
								}, 2000);
							} catch (err) {
								console.error('Failed to copy text: ', err);
							}
						};
						wrapper.appendChild(button);
					}
				}
			});

			// Attach change listeners to checkboxes
			node.querySelectorAll('input[type="checkbox"]').forEach((checkbox, index) => {
				const input = checkbox as HTMLInputElement;
				// Ensure we only attach once
				if (!input.hasAttribute('data-interactive-bound')) {
					input.setAttribute('data-interactive-bound', 'true');
					input.onchange = (e) => {
						e.stopPropagation();
						handleCheckboxChange(index, input.checked);
					};
					input.onclick = (e) => {
						e.stopPropagation();
					};
				}
			});

			// 埋め込み（note-embed:リンク）を本文に展開
			node.querySelectorAll('a[href^="note-embed:"]').forEach((anchor) => {
				const embedLink = anchor as HTMLAnchorElement;
				if (embedLink.hasAttribute('data-embed-bound')) return;
				embedLink.setAttribute('data-embed-bound', 'true');

				const href = embedLink.getAttribute('href') || '';
				const title = decodeURIComponent(href.replace('note-embed:', ''));
				const wrapper = document.createElement('div');
				wrapper.className =
					'note-embed-wrapper border-l-4 border-primary pl-4 py-2 my-4 bg-base-200/30 rounded-r-lg';
				wrapper.innerHTML = `
					<div class="text-xs text-base-content/50 mb-2 font-semibold flex items-center justify-between">
						<div class="flex items-center gap-1">
							<span>🔗</span>
							<span>埋め込み: ${escapeHtml(title)}</span>
						</div>
					</div>
					<div class="note-embed-content prose prose-sm max-w-none opacity-80">
						<span class="loading loading-dots loading-sm"></span>
					</div>
				`;

				const content = wrapper.querySelector('.note-embed-content') as HTMLElement | null;
				embedLink.replaceWith(wrapper);

				if (!content || !title) return;

				fetch(`/api/notes/embed?title=${encodeURIComponent(title)}`)
					.then((res) => {
						if (!res.ok) throw new Error('Not found');
						return res.json() as Promise<{ content?: string }>;
					})
					.then((data) => {
						const parsed = customMarked.parse(data.content || '', { breaks: true }) as string;
						content.innerHTML = sanitizeHtml(parsed);
					})
					.catch(() => {
						content.textContent = `ノート「${title}」が見つかりませんでした。`;
						content.className = 'text-error text-sm mt-2 block';
					});
			});
		};

		// Run initially after DOM settles
		setTimeout(applyEnhancements, 0);

		return {
			update() {
				setTimeout(applyEnhancements, 0);
			}
		};
	}

	async function handleCheckboxChange(index: number, isChecked: boolean) {
		if (!note.content) return;

		let newContent = note.content;

		if (isHtmlContent) {
			const parser = new DOMParser();
			const doc = parser.parseFromString(newContent, 'text/html');
			const checkboxes = doc.querySelectorAll('input[type="checkbox"]');

			if (checkboxes[index]) {
				const checkbox = checkboxes[index] as HTMLInputElement;
				if (isChecked) {
					checkbox.setAttribute('checked', 'checked');
				} else {
					checkbox.removeAttribute('checked');
				}

				const li = checkbox.closest('li[data-type="taskItem"]');
				if (li) {
					li.setAttribute('data-checked', isChecked ? 'true' : 'false');
				}
				newContent = doc.body.innerHTML;
			}
		} else {
			// Markdown approach
			let matchCount = 0;
			// Match a markdown list item with checkbox like "- [ ] " or "* [x] "
			newContent = newContent.replace(/^(\s*[-*+]\s+)\[([ xX])\]/gm, (match, prefix) => {
				if (matchCount === index) {
					matchCount++;
					return `${prefix}[${isChecked ? 'x' : ' '}]`;
				}
				matchCount++;
				return match;
			});
		}

		if (newContent !== note.content) {
			newContent = normalizeContentForStorage(newContent);

			const oldContent = note.content;
			note.content = newContent; // Optimistic update
			try {
				const response = await fetch(`/api/notes/${note.id}`, {
					method: 'PUT',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({ content: newContent })
				});
				if (!response.ok) {
					console.error('Failed to update check status');
					note.content = oldContent; // Revert on failure
				} else {
					// Refresh list so other UI parts (like note view) show the right state
					await invalidateAll();
				}
			} catch (e) {
				console.error('Error updating checkbox', e);
				note.content = oldContent; // Revert on failure
			}
		}
	}

	let interactionDebounce = false;
	function handleInteraction() {
		if (interactionDebounce) return;
		interactionDebounce = true;

		console.log('Edit event dispatched for note:', note);
		dispatch('edit', note);

		setTimeout(() => {
			interactionDebounce = false;
		}, 300);
	}

	let element: HTMLElement;
	let deleteDialog: HTMLDialogElement;
	let touchStartX = 0;
	let touchStartY = 0;
	let touchCurrentX = 0;
	let isSwiping = false;
	const swipeThreshold = 100; // Swipe distance in pixels to trigger action

	function handleTouchStart(e: TouchEvent) {
		// Don't start swipe if touching an interactive element
		const target = e.target as HTMLElement;
		if (target.closest('button, input, a, [role="button"]')) {
			isSwiping = false;
			return;
		}

		touchStartX = e.touches[0].clientX;
		touchStartY = e.touches[0].clientY; // Track Y for scroll detection
		touchCurrentX = touchStartX;
		isSwiping = true;
	}

	function handleTouchMove(e: TouchEvent) {
		if (!isSwiping) return;
		touchCurrentX = e.touches[0].clientX;
		const touchCurrentY = e.touches[0].clientY;

		const diffX = touchCurrentX - touchStartX;
		const diffY = touchCurrentY - touchStartY;

		// If user is scrolling vertically more than horizontally, cancel swipe
		if (Math.abs(diffY) > Math.abs(diffX) && Math.abs(diffY) > 10) {
			isSwiping = false;
			element.style.transform = 'translateX(0)';
			return;
		}

		// Prevent default only if we are horizontally swiping to avoid blocking scroll
		if (Math.abs(diffX) > 10) {
			// e.preventDefault(); // Might cause issues in some browsers
			element.style.transform = `translateX(${diffX}px)`;
		}
	}

	function handleTouchEnd() {
		if (!isSwiping) return;
		const diff = touchCurrentX - touchStartX;

		// Reset style
		element.style.transform = 'translateX(0)';
		isSwiping = false;

		if (mode === 'timeline') {
			if (diff > swipeThreshold) {
				// Right swipe
				sendToBox();
			} else if (diff < -swipeThreshold) {
				// Left swipe
				sendToArchive();
			}
		}

		touchStartX = 0;
		touchCurrentX = 0;
	}

	async function updateNoteStatus(status: 'inbox' | 'box' | 'archived' | 'trash') {
		try {
			const response = await fetch(`/api/notes/${note.id}/status`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ status })
			});
			if (response.ok) {
				await invalidateAll();
			} else {
				console.error(`Failed to move note to ${status}`);
			}
		} catch (error) {
			console.error('Error updating note status:', error);
		}
	}

	async function togglePin() {
		try {
			const response = await fetch(`/api/notes/${note.id}/pin`, {
				method: 'POST'
			});
			if (response.ok) {
				await invalidateAll();
			} else {
				console.error('Failed to toggle pin');
			}
		} catch (error) {
			console.error('Error toggling pin:', error);
		}
	}

	function openDeleteModal() {
		if (deleteDialog) {
			deleteDialog.showModal();
		}
	}

	async function deletePermanently() {
		try {
			const response = await fetch(`/api/notes/${note.id}`, {
				method: 'DELETE'
			});
			if (response.ok) {
				if (deleteDialog) deleteDialog.close();
				dispatch('delete', note);
				await invalidateAll();
			} else {
				console.error('Failed to delete note permanently');
			}
		} catch (error) {
			console.error('Error deleting note permanently:', error);
		}
	}

	const sendToBox = () => updateNoteStatus('box');
	const sendToArchive = () => updateNoteStatus('archived');
	const sendToTrash = () => updateNoteStatus('trash');
	const restoreToInbox = () => updateNoteStatus('inbox');

	const formattedDate = formatDistanceToNow(new Date(note.updatedAt), {
		addSuffix: true,
		locale: ja
	});
</script>

<div
	bind:this={element}
	class="card bg-base-100 shadow-md transition-transform duration-200 ease-in-out select-none"
	ontouchstart={handleTouchStart}
	ontouchmove={handleTouchMove}
	ontouchend={handleTouchEnd}
	role="article"
	aria-label={note.title || 'メモ'}
>
	<div class="card-body p-4">
		{#if note.isPinned}
			<div class="text-primary absolute top-2 right-2">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="h-5 w-5"
					viewBox="0 0 20 20"
					fill="currentColor"
				>
					<path
						d="M16 12V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v8l-2 2v2h5.2v5l1.8 2 1.8-2v-5H18v-2l-2-2z"
					/>
				</svg>
			</div>
		{/if}

		{#if note.title && note.title !== 'Untitled Note'}
			<h2 class="mb-2 text-xl font-bold">{note.title}</h2>
		{/if}

		<div class="prose text-base-content max-w-none" use:enhanceProseContent={contentWithEmbeds}>
			{#if isHtmlContent}
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html sanitizeHtml(contentWithEmbeds || '')}
			{:else}
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html sanitizeHtml(customMarked.parse(contentWithEmbeds || '', { breaks: true }) as string)}
			{/if}
		</div>

		<div class="text-base-content/60 mt-4 flex items-center justify-between text-xs">
			<span>{formattedDate}</span>
			<div class="card-actions">
				<button class="btn btn-ghost btn-xs" onclick={handleInteraction}> Edit </button>
				{#if mode === 'timeline'}
					<button
						class="btn btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							togglePin();
						}}
					>
						{note.isPinned ? 'Unpin' : 'Pin'}
					</button>
					<button
						class="btn btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							sendToBox();
						}}
					>
						Box
					</button>
					<button
						class="btn btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							sendToArchive();
						}}
					>
						Archive
					</button>
				{:else if mode === 'archive'}
					<button
						class="btn btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							restoreToInbox();
						}}
					>
						Restore
					</button>
					<button
						class="btn btn-error btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							sendToTrash();
						}}
					>
						Trash
					</button>
				{:else if mode === 'trash'}
					<button
						class="btn btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							restoreToInbox();
						}}
					>
						Restore
					</button>
					<button
						class="btn btn-error btn-ghost btn-xs"
						onclick={(e) => {
							e.stopPropagation();
							openDeleteModal();
						}}
					>
						Delete
					</button>
				{/if}
			</div>
		</div>
	</div>
</div>

<!-- 削除確認モーダル -->
<dialog bind:this={deleteDialog} class="modal">
	<div class="modal-box text-left">
		<h3 class="text-error text-lg font-bold">削除の確認</h3>
		<p class="text-base-content py-4 whitespace-normal">
			このノートを完全に削除しますか？この操作は取り消せません。
		</p>
		<div class="modal-action">
			<form method="dialog">
				<button class="btn">キャンセル</button>
			</form>
			<button
				class="btn btn-error"
				onclick={(e) => {
					e.stopPropagation();
					deletePermanently();
				}}
			>
				削除する
			</button>
		</div>
	</div>
	<form method="dialog" class="modal-backdrop">
		<button>close</button>
	</form>
</dialog>
